services:
  - type: web
    name: ai-log-analyzer
    runtime: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
